[package]
name = "modern-cug-report"
version = "0.1.3"
entrypoint = "lib.typ"
authors = ["Dongdong Kong"]
license = "MIT"
description = "Chinese Technical report writing standards."
compiler = "0.13.1"
repository = "https://github.com/CUG-hydro/modern-cug-report.typ"
exclude = ["example", ".gitignore"]
categories = ["layout", "report"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "../thumbnail.png"
